version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    container_name: brand-analysis-neo4j
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/password123
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms_memory_heap_max__size=2G
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    networks:
      - brand-analysis-network
    restart: unless-stopped

  # Uncomment to run the API service in Docker
  # api:
  #   build: .
  #   container_name: brand-analysis-api
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - NEO4J_URI=bolt://neo4j:7687
  #     - NEO4J_USER=neo4j
  #     - NEO4J_PASSWORD=password123
  #     - OPENAI_API_KEY=${OPENAI_API_KEY}
  #     - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
  #   depends_on:
  #     - neo4j
  #   networks:
  #     - brand-analysis-network
  #   restart: unless-stopped

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:

networks:
  brand-analysis-network:
    driver: bridge

